# Maven
# Build your Java project and run tests with Apache Maven.

trigger:
- main

pool:
  name: Default  # Use the Default pool 
  demands:
    - agent.name -equals Hrithiks-MacBook-Air  # local agent name

steps:
- script: |
    echo "Running on $(Agent.Name)"
    java -version  # Verify Java installation
  displayName: 'Verify Agent and Java Installation'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'path'
    jdkDirectory: '/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home' # Ensure this is your Java path
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    isJacocoCoverageReportXML: true
    goals: 'clean verify jacoco:report package'
